# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: Smart
networks:
- id: 10143
  start_block: 0
  contracts:
  - name: smart
    address:
    - 0xFf71Ff614d6B621541408Adce546bF68Ad399b5d
    handler: src/EventHandlers.ts
    events:
    - event: BatchTransferExecuted(address indexed smartAccount, uint256 recipientCount, uint256 totalValue, string transferType, address tokenAddress, uint256 timestamp, bytes32 indexed userOpHash)
    - event: TransferExecuted(address indexed smartAccount, address indexed to, uint256 value, string transferType, address tokenAddress, uint256 timestamp, bytes32 indexed userOpHash)
unordered_multichain_mode: true
preload_handlers: true
